services:
  crm_db:
    image: postgres:15-alpine
    container_name: crm_postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=crm_admin
      - POSTGRES_PASSWORD=crm_secret_password
      - POSTGRES_DB=crm_production_db   # âœ… no spaces
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
